services:
  database:
    image: postgres:18-alpine
    container_name: catalog-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
